#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : exiv2
Version  : 0.25
Release  : 6
URL      : http://www.exiv2.org/exiv2-0.25.tar.gz
Source0  : http://www.exiv2.org/exiv2-0.25.tar.gz
Summary  : Image metadata library and tools
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0
Requires: exiv2-bin
Requires: exiv2-lib
Requires: exiv2-locales
Requires: exiv2-doc
BuildRequires : cmake
BuildRequires : expat-dev
BuildRequires : pkgconfig(zlib)
BuildRequires : zlib-dev

%description
Exiv2
*****
Welcome to Exiv2, a C++ library and a command line utility to read and
write Exif, IPTC and XMP image metadata. The homepage of Exiv2 is:

%package bin
Summary: bin components for the exiv2 package.
Group: Binaries

%description bin
bin components for the exiv2 package.


%package dev
Summary: dev components for the exiv2 package.
Group: Development
Requires: exiv2-lib
Requires: exiv2-bin
Provides: exiv2-devel

%description dev
dev components for the exiv2 package.


%package doc
Summary: doc components for the exiv2 package.
Group: Documentation

%description doc
doc components for the exiv2 package.


%package lib
Summary: lib components for the exiv2 package.
Group: Libraries

%description lib
lib components for the exiv2 package.


%package locales
Summary: locales components for the exiv2 package.
Group: Default

%description locales
locales components for the exiv2 package.


%prep
%setup -q -n exiv2-0.25

%build
export LANG=C
export SOURCE_DATE_EPOCH=1487024810
%configure --disable-static
make V=1  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1487024810
rm -rf %{buildroot}
%make_install
%find_lang exiv2

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/exiv2

%files dev
%defattr(-,root,root,-)
/usr/include/exiv2/basicio.hpp
/usr/include/exiv2/bmpimage.hpp
/usr/include/exiv2/config.h
/usr/include/exiv2/convert.hpp
/usr/include/exiv2/cr2image.hpp
/usr/include/exiv2/crwimage.hpp
/usr/include/exiv2/datasets.hpp
/usr/include/exiv2/easyaccess.hpp
/usr/include/exiv2/epsimage.hpp
/usr/include/exiv2/error.hpp
/usr/include/exiv2/exif.hpp
/usr/include/exiv2/exiv2.hpp
/usr/include/exiv2/exv_conf.h
/usr/include/exiv2/exv_msvc.h
/usr/include/exiv2/futils.hpp
/usr/include/exiv2/gifimage.hpp
/usr/include/exiv2/http.hpp
/usr/include/exiv2/image.hpp
/usr/include/exiv2/iptc.hpp
/usr/include/exiv2/jp2image.hpp
/usr/include/exiv2/jpgimage.hpp
/usr/include/exiv2/metadatum.hpp
/usr/include/exiv2/mrwimage.hpp
/usr/include/exiv2/orfimage.hpp
/usr/include/exiv2/pgfimage.hpp
/usr/include/exiv2/pngimage.hpp
/usr/include/exiv2/preview.hpp
/usr/include/exiv2/properties.hpp
/usr/include/exiv2/psdimage.hpp
/usr/include/exiv2/rafimage.hpp
/usr/include/exiv2/rw2image.hpp
/usr/include/exiv2/svn_version.h
/usr/include/exiv2/tags.hpp
/usr/include/exiv2/tgaimage.hpp
/usr/include/exiv2/tiffimage.hpp
/usr/include/exiv2/types.hpp
/usr/include/exiv2/value.hpp
/usr/include/exiv2/version.hpp
/usr/include/exiv2/xmp.hpp
/usr/include/exiv2/xmpsidecar.hpp
/usr/lib64/libexiv2.so
/usr/lib64/pkgconfig/exiv2.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libexiv2.so.14
/usr/lib64/libexiv2.so.14.0.0

%files locales -f exiv2.lang
%defattr(-,root,root,-)

